import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How Yupzee collects, uses, and protects your personal data.",
};

const sections = [
  {
    title: "1. Who we are",
    content:
      'Yupzee Ltd (\u201cYupzee\u201d, \u201cwe\u201d, \u201cour\u201d, \u201cus\u201d) operates the Yupzee mobile application and website. We are the data controller for the personal data we collect from you. If you have any questions about this policy, please contact us at hello@yupzee.com.',
  },
  {
    title: "2. What data we collect",
    content:
      "We collect information you provide directly (e.g. name, university email address, profile information), information generated by your use of the app (e.g. posts, event RSVPs, job applications, connections), technical data (e.g. IP address, device identifiers, browser type), and usage data (e.g. pages viewed, features used, time spent in the app).",
  },
  {
    title: "3. How we use your data",
    content:
      "We use your data to: provide and improve the Yupzee service; personalise your feed and recommendations; send you notifications and announcements; facilitate connections between users; verify your university affiliation; comply with legal obligations; and (with your consent) send marketing communications.",
  },
  {
    title: "4. Legal basis for processing",
    content:
      "We process your data on the following legal bases: performance of a contract (providing the Yupzee service); legitimate interests (improving our service, preventing fraud); legal obligations (complying with applicable law); and consent (where we ask for it, such as for marketing emails or optional cookies).",
  },
  {
    title: "5. Sharing your data",
    content:
      "We do not sell your personal data. We may share data with: trusted third-party service providers who help us operate Yupzee (e.g. cloud hosting, analytics); your university where you have connected your university account; and law enforcement or regulatory authorities where required by law.",
  },
  {
    title: "6. Data retention",
    content:
      "We retain your data for as long as your account is active, or as long as necessary to provide the service. When you delete your account, we will delete or anonymise your personal data within 30 days, except where we are required to retain it by law.",
  },
  {
    title: "7. Your rights",
    content:
      "Under UK GDPR and the Data Protection Act 2018, you have the right to: access your personal data; correct inaccurate data; request deletion of your data; object to processing; restrict processing; data portability; and withdraw consent at any time. To exercise these rights, contact hello@yupzee.com.",
  },
  {
    title: "8. Cookies",
    content:
      "We use cookies and similar technologies to operate and improve our service. For detailed information, see our Cookie Policy.",
  },
  {
    title: "9. Security",
    content:
      "We implement appropriate technical and organisational measures to protect your data, including encryption in transit and at rest, access controls, and regular security assessments. However, no transmission over the internet is 100% secure.",
  },
  {
    title: "10. International transfers",
    content:
      "Your data may be transferred to and processed in countries outside the UK. Where we transfer data internationally, we ensure appropriate safeguards are in place in accordance with UK data protection law.",
  },
  {
    title: "11. Children",
    content:
      "Yupzee is intended for users aged 16 and over. We do not knowingly collect personal data from children under 16. If you believe a child has provided us with personal data, please contact us at hello@yupzee.com.",
  },
  {
    title: "12. Changes to this policy",
    content:
      "We may update this Privacy Policy from time to time. We will notify you of significant changes via the app or email. Your continued use of Yupzee after any changes constitutes acceptance of the updated policy.",
  },
  {
    title: "13. Contact us",
    content:
      "For any privacy-related questions or to exercise your rights, please email hello@yupzee.com or write to: Data Protection Officer, Yupzee Ltd, [Address], United Kingdom.",
  },
];

export default function PrivacyPage() {
  return (
    <section className="py-16 bg-white">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-10">
          <p className="text-xs font-semibold text-primary uppercase tracking-widest mb-2">
            Legal
          </p>
          <h1 className="text-4xl font-bold text-gray-900 mb-3">
            Privacy Policy
          </h1>
          <p className="text-gray-500 text-sm">Last updated: 1 March 2026</p>
        </div>

        <div className="prose prose-gray max-w-none">
          <p className="text-gray-600 leading-relaxed mb-10 text-base">
            At Yupzee, your privacy matters. This Privacy Policy explains what
            personal data we collect, why we collect it, and how we use it when
            you use the Yupzee app and website. Please read it carefully.
          </p>

          <div className="space-y-8">
            {sections.map((s) => (
              <div key={s.title}>
                <h2 className="text-lg font-semibold text-gray-900 mb-3">
                  {s.title}
                </h2>
                <p className="text-gray-600 leading-relaxed text-base">
                  {s.content}
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
